'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  setAI: (cfg) => ipcRenderer.invoke('ai:set', cfg),
  detectEngines: () => ipcRenderer.invoke('ai:detect'),
  parseRoster: (text) => ipcRenderer.invoke('roster:parse', { text }),
  saveRoster: (data) => ipcRenderer.invoke('roster:save', data),
  loadDemo: () => ipcRenderer.invoke('demo:load'),
  runSync: (opts) => ipcRenderer.invoke('run:sync', opts),
  runNow: () => ipcRenderer.invoke('run:now'),
  credsStatus: () => ipcRenderer.invoke('creds:status'),
  saveCreds: (creds) => ipcRenderer.invoke('creds:save', creds),
  syncRun: (opts) => ipcRenderer.invoke('sync:run', opts || {}),
  captureFields: () => ipcRenderer.invoke('capture:fields'),
  runSiteDemo: (opts) => ipcRenderer.invoke('demo:run-site', opts),
  onDemoStep: (cb) => ipcRenderer.on('demo-step', (_e, s) => cb(s)),
  recordStart: (opts) => ipcRenderer.invoke('record:start', opts || {}),
  recordStop: () => ipcRenderer.invoke('record:stop'),
  recordSave: (data) => ipcRenderer.invoke('record:save', data),
  recordList: () => ipcRenderer.invoke('record:list'),
  recordDelete: (id) => ipcRenderer.invoke('record:delete', { id }),
  recordReplay: (opts) => ipcRenderer.invoke('record:replay', opts || {}),
  onRecordEvent: (cb) => ipcRenderer.on('record-event', (_e, s) => cb(s)),
  teach: (target, url) => ipcRenderer.invoke('teach:run', { target, url }),
  onRunStatus: (cb) => ipcRenderer.on('run-status', (_e, s) => cb(s)),
  onRunFinished: (cb) => ipcRenderer.on('run-finished', (_e, r) => cb(r)),
  onLiveStep: (cb) => ipcRenderer.on('live-step', (_e, s) => cb(s)),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, s) => cb(s)),
  alertsList: () => ipcRenderer.invoke('alerts:list'),
  alertsClear: () => ipcRenderer.invoke('alerts:clear'),
  onAlertAdded: (cb) => ipcRenderer.on('alert-added', (_e, a) => cb(a)),
});
